//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceGamusinoFantasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enemy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enemy()
        {
            this.Enemy_Drop = new HashSet<Enemy_Drop>();
            this.EnemyAssignedToAMissions = new HashSet<EnemyAssignedToAMission>();
            this.Players = new HashSet<Player>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public long vitalityBase { get; set; }
        public long strengthBase { get; set; }
        public long resistanceBase { get; set; }
        public long speedBase { get; set; }
        public long experience { get; set; }
        public string rank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enemy_Drop> Enemy_Drop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnemyAssignedToAMission> EnemyAssignedToAMissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
    }
}
