//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceGamusinoFantasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enemy_Drop
    {
        public long Item_id { get; set; }
        public long Enemy_id { get; set; }
        public Nullable<decimal> dropRate { get; set; }
    
        public virtual Enemy Enemy { get; set; }
        public virtual Item Item { get; set; }
    }
}
