//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceGamusinoFantasy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamusinosFantasyEntities : DbContext
    {
        public GamusinosFantasyEntities()
            : base("name=GamusinosFantasyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Armor> Armors { get; set; }
        public virtual DbSet<Armor_Craft> Armor_Craft { get; set; }
        public virtual DbSet<Backpack> Backpacks { get; set; }
        public virtual DbSet<Backpack_Items> Backpack_Items { get; set; }
        public virtual DbSet<Enemy> Enemies { get; set; }
        public virtual DbSet<Enemy_Drop> Enemy_Drop { get; set; }
        public virtual DbSet<EnemyAssignedToAMission> EnemyAssignedToAMissions { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Inventory_Items> Inventory_Items { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Reward> Rewards { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Weapon> Weapons { get; set; }
        public virtual DbSet<Weapon_Craft> Weapon_Craft { get; set; }
        public virtual DbSet<SelectedMission> SelectedMissions { get; set; }
        public virtual DbSet<CombatLog> CombatLogs { get; set; }
        public virtual DbSet<Mission> Missions { get; set; }
    }
}
