//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceGamusinoFantasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Users = new HashSet<User>();
            this.SelectedMissions = new HashSet<SelectedMission>();
            this.Enemies = new HashSet<Enemy>();
            this.CompletedMissions = new HashSet<Mission>();
        }
    
        public long id { get; set; }
        public long expPoints { get; set; }
        public long vitality { get; set; }
        public long resistance { get; set; }
        public long force { get; set; }
        public long speed { get; set; }
        public long luck { get; set; }
        public long Inventory_id { get; set; }
        public long Backpack_id { get; set; }
        public long Weapon_id { get; set; }
        public long Armor_id { get; set; }
        public string rank { get; set; }
    
        public virtual Armor Armor { get; set; }
        public virtual Backpack Backpack { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Weapon Weapon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedMission> SelectedMissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enemy> Enemies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mission> CompletedMissions { get; set; }
    }
}
